import { ArchitectureTemplate, TemplateCategory } from '../template-types';

export const eventDrivenKafkaTemplate: ArchitectureTemplate = {
  id: 'event-driven-kafka',
  name: 'Event-Driven Architecture',
  description: 'Event-driven system using Kafka for async communication between services',
  category: TemplateCategory.EVENT_DRIVEN,
  tags: ['event-driven', 'kafka', 'async', 'messaging', 'cqrs'],
  difficulty: 'advanced',
  author: 'FlowForge',
  nodes: [
    // Producer Services
    {
      id: 'user-action-service',
      type: 'container-service',
      position: { x: 100, y: 100 },
      data: {
        label: 'User Action Service',
        description: 'Captures user actions and publishes events',
        technology: 'Node.js, Express',
        category: 'api',
        level: 'container',
        color: '#2196F3',
      },
    },
    {
      id: 'order-service',
      type: 'container-service',
      position: { x: 100, y: 300 },
      data: {
        label: 'Order Service',
        description: 'Manages orders and publishes order events',
        technology: 'Java, Spring Boot',
        category: 'api',
        level: 'container',
        color: '#2196F3',
      },
    },
    {
      id: 'payment-service',
      type: 'container-service',
      position: { x: 100, y: 500 },
      data: {
        label: 'Payment Service',
        description: 'Processes payments and publishes payment events',
        technology: 'Python, FastAPI',
        category: 'api',
        level: 'container',
        color: '#2196F3',
      },
    },
    
    // Kafka Topics
    {
      id: 'user-events-topic',
      type: 'external-system',
      position: { x: 450, y: 100 },
      data: {
        label: 'user-events',
        description: 'User action events topic',
        technology: 'Kafka Topic',
        category: 'kafka-topic',
        level: 'container',
        color: '#FF5722',
      },
    },
    {
      id: 'order-events-topic',
      type: 'external-system',
      position: { x: 450, y: 300 },
      data: {
        label: 'order-events',
        description: 'Order lifecycle events topic',
        technology: 'Kafka Topic',
        category: 'kafka-topic',
        level: 'container',
        color: '#FF5722',
      },
    },
    {
      id: 'payment-events-topic',
      type: 'external-system',
      position: { x: 450, y: 500 },
      data: {
        label: 'payment-events',
        description: 'Payment transaction events topic',
        technology: 'Kafka Topic',
        category: 'kafka-topic',
        level: 'container',
        color: '#FF5722',
      },
    },
    
    // Consumer Services
    {
      id: 'analytics-service',
      type: 'container-service',
      position: { x: 800, y: 100 },
      data: {
        label: 'Analytics Service',
        description: 'Consumes events for real-time analytics',
        technology: 'Python, Apache Spark',
        category: 'api',
        level: 'container',
        color: '#2196F3',
      },
    },
    {
      id: 'notification-service',
      type: 'container-service',
      position: { x: 800, y: 300 },
      data: {
        label: 'Notification Service',
        description: 'Sends notifications based on events',
        technology: 'Node.js',
        category: 'api',
        level: 'container',
        color: '#2196F3',
      },
    },
    {
      id: 'inventory-service',
      type: 'container-service',
      position: { x: 800, y: 500 },
      data: {
        label: 'Inventory Service',
        description: 'Updates inventory based on order events',
        technology: 'Go',
        category: 'api',
        level: 'container',
        color: '#2196F3',
      },
    },
    
    // Databases
    {
      id: 'analytics-db',
      type: 'database',
      position: { x: 1100, y: 100 },
      data: {
        label: 'Analytics DB',
        description: 'Time-series data for analytics',
        technology: 'ClickHouse',
        category: 'database',
        level: 'container',
        color: '#2196F3',
      },
    },
    {
      id: 'inventory-db',
      type: 'database',
      position: { x: 1100, y: 500 },
      data: {
        label: 'Inventory DB',
        description: 'Inventory state storage',
        technology: 'PostgreSQL',
        category: 'database',
        level: 'container',
        color: '#2196F3',
      },
    },
  ],
  edges: [
    // Producers → Topics
    {
      id: 'e-user-topic',
      source: 'user-action-service',
      target: 'user-events-topic',
      type: 'editable',
      animated: true,
      data: { label: 'Publish', edgeStyle: 'dashed' },
      style: { stroke: '#FF5722', strokeWidth: 3 },
      markerEnd: { type: 'arrowclosed' as const, color: '#FF5722' },
    },
    {
      id: 'e-order-topic',
      source: 'order-service',
      target: 'order-events-topic',
      type: 'editable',
      animated: true,
      data: { label: 'Publish', edgeStyle: 'dashed' },
      style: { stroke: '#FF5722', strokeWidth: 3 },
      markerEnd: { type: 'arrowclosed' as const, color: '#FF5722' },
    },
    {
      id: 'e-payment-topic',
      source: 'payment-service',
      target: 'payment-events-topic',
      type: 'editable',
      animated: true,
      data: { label: 'Publish', edgeStyle: 'dashed' },
      style: { stroke: '#FF5722', strokeWidth: 3 },
      markerEnd: { type: 'arrowclosed' as const, color: '#FF5722' },
    },
    
    // Topics → Consumers
    {
      id: 'e-topic-analytics',
      source: 'user-events-topic',
      target: 'analytics-service',
      type: 'editable',
      animated: true,
      data: { label: 'Subscribe', edgeStyle: 'dashed' },
      style: { stroke: '#4CAF50', strokeWidth: 3 },
      markerEnd: { type: 'arrowclosed' as const, color: '#4CAF50' },
    },
    {
      id: 'e-order-notification',
      source: 'order-events-topic',
      target: 'notification-service',
      type: 'editable',
      animated: true,
      data: { label: 'Subscribe', edgeStyle: 'dashed' },
      style: { stroke: '#4CAF50', strokeWidth: 3 },
      markerEnd: { type: 'arrowclosed' as const, color: '#4CAF50' },
    },
    {
      id: 'e-order-inventory',
      source: 'order-events-topic',
      target: 'inventory-service',
      type: 'editable',
      animated: true,
      data: { label: 'Subscribe', edgeStyle: 'dashed' },
      style: { stroke: '#4CAF50', strokeWidth: 3 },
      markerEnd: { type: 'arrowclosed' as const, color: '#4CAF50' },
    },
    {
      id: 'e-payment-notification',
      source: 'payment-events-topic',
      target: 'notification-service',
      type: 'editable',
      animated: true,
      data: { label: 'Subscribe', edgeStyle: 'dashed' },
      style: { stroke: '#4CAF50', strokeWidth: 3 },
      markerEnd: { type: 'arrowclosed' as const, color: '#4CAF50' },
    },
    
    // Consumers → Databases
    {
      id: 'e-analytics-db',
      source: 'analytics-service',
      target: 'analytics-db',
      type: 'editable',
      data: { label: 'Insert', edgeStyle: 'solid' },
      style: { stroke: '#3B82F6', strokeWidth: 3 },
      markerEnd: { type: 'arrowclosed' as const, color: '#3B82F6' },
    },
    {
      id: 'e-inventory-db',
      source: 'inventory-service',
      target: 'inventory-db',
      type: 'editable',
      data: { label: 'Update', edgeStyle: 'solid' },
      style: { stroke: '#3B82F6', strokeWidth: 3 },
      markerEnd: { type: 'arrowclosed' as const, color: '#3B82F6' },
    },
  ],
};